### ISSUE TITLE
【错误回报】疑似兼容性错误

### ISSUE THREAD

**Issue by NAOLIU** [nonebot/plugin-apscheduler#8] opened 2022-04-22 08:48 UTC
在使用
https://github.com/nonepkg/nonebot-plugin-mcstatus/issues/4
这个MC服务器查询插件的时候，插件运行时，一直在报这个INFO，导致有点刷屏
插件作者说可能是本插件的问题

04-22 16:17:30 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False>
04-22 16:17:30 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False> running complete
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcstatus\utils.py:104: DeprecationWarning: 'MinecraftServer' is deprecated and is expected to be removed on 2022-08, use 'JavaServer' instead.
  warnings.warn(warn_message, category=DeprecationWarning)
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcstatus\utils.py:104: DeprecationWarning: 'MinecraftServer' is deprecated and is expected to be removed on 2022-08, use 'JavaServer' instead.
  warnings.warn(warn_message, category=DeprecationWarning)
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_content.py:203: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
  warnings.warn(message, DeprecationWarning)

**Comment by yanyongyu** [comment] 2022-04-22 09:22
上游apscheduler问题，duplicate of #7

**Closed by yanyongyu** 2022-04-22 09:22 UTC
